image:
  # image.repository -- MOCO image repository to use.
  repository: ghcr.io/cybozu-go/moco

  # image.tag -- MOCO image tag to use.
  # @default -- `{{ .Chart.AppVersion }}`
  tag:  # 0.20.2

# resources -- resources used by moco-controller.
resources:
  requests:
    cpu: 100m
    memory: 20Mi

crds:
  # crds.enabled -- Install and update CRDs as part of the Helm chart.
  enabled: true

# extraArgs -- Additional command line flags to pass to moco-controller binary.
extraArgs: []

# nodeSelector -- nodeSelector used by moco-controller.
nodeSelector: {}

# affinity -- affinity used by moco-controller.
affinity: {}

# tolerations -- tolerations used by moco-controller.
tolerations: []

# topologySpreadConstraints -- topologySpreadConstraints used by moco-controller.
topologySpreadConstraints: []

# priorityClassName -- PriorityClass used by moco-controller.
priorityClassName: ""
