resources:
  - ../../../crd

patchesStrategicMerge:
  - conversion-patch.yaml

commonLabels:
  app.kubernetes.io/name: moco

commonAnnotations:
  helm.sh/resource-policy: keep

transformers:
  - label-transformer.yaml
