name: Integration tests with MySQL

on:
  workflow_call:
    inputs:
      mysql-version:
        required: true
        type: string
      ref:
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  dbtest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
      - run: make setup
      - run: make test-bkop MYSQL_VERSION=${{ inputs.mysql-version }}
      - run: make test-dbop MYSQL_VERSION=${{ inputs.mysql-version }}
