name: handle PR comments
on:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  pull-requests: write
  actions: write

jobs:
  check_permission:
    name: "Check permission"
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/test')
    runs-on: ubuntu-22.04
    outputs:
      permission: ${{ steps.check_permission.outputs.permission }}
    steps:
      - name: check permission
        id: check_permission
        run: |
          # https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
          allow_permissions=("OWNER", "COLLABORATOR", "MEMBER")
          echo "user association is ${{ github.event.comment.author_association }}"
          if echo "${allow_permissions[@]}" | grep -qw "${{ github.event.comment.author_association }}"; then
            echo "allow"
            echo "permission=allow" >> $GITHUB_OUTPUT
          else
            echo "deny"
            echo "To trigger the e2e test, the user must be an OWNER, COLLABORATOR, or MEMBER."
            echo "permission=deny" >> $GITHUB_OUTPUT
          fi
  trigger_e2e:
    name: "Trigger e2e test"
    needs: check_permission
    if: ${{ needs.check_permission.outputs.permission == 'allow' }}
    runs-on: ubuntu-22.04
    steps:
      - name: create reaction
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # https://docs.github.com/ja/rest/reactions/reactions?apiVersion=2022-11-28#create-reaction-for-an-issue-comment
          # needs pull_requests:write permission
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            -f content='rocket'
      - uses: actions/checkout@v4
      - name: trigger e2e
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BRANCH_NAME=$(gh pr view --json headRefName --jq .headRefName ${{ github.event.issue.number }})
          echo "triggering e2e"
          gh workflow run --ref ${BRANCH_NAME} ci-e2e.yaml
