name: handle PR comments
on:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  pull-requests: write
  actions: write

jobs:
  trigger_e2e:
    name: "Trigger e2e test"
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/test') && contains('["OWNER", "COLLABORATOR", "MEMBER"]', github.event.comment.author_association)
    runs-on: ubuntu-22.04
    steps:
      - name: create reaction
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # https://docs.github.com/ja/rest/reactions/reactions?apiVersion=2022-11-28#create-reaction-for-an-issue-comment
          # needs pull_requests:write permission
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            -f content='rocket'
      - uses: actions/checkout@v4
      - name: trigger e2e
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BRANCH_NAME=$(gh pr view --json headRefName --jq .headRefName ${{ github.event.issue.number }})
          echo "triggering e2e"
          gh workflow run --ref ${BRANCH_NAME} ci-e2e.yaml
